# .github/workflows/publish.yml

name: Publish Arabic Library to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: " 3.7 and up "  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build
        echo "Package version: $(python setup.py --version)"

    - name: Verify distributions
      run: |
        ls -lh dist/
        twine check dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  

    environment:
      name: pypi
      url: https://pypi.org/project/arabic-library/

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
